# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name=b'Name')),
                ('email', models.EmailField(blank=True, max_length=128, null=True, verbose_name=b'Email')),
                ('phone', models.CharField(blank=True, max_length=128, null=True, verbose_name=b'Phone Number')),
            ],
        ),
    ]
